### ISSUE TITLE
Styled before each component name?

### ISSUE THREAD

**Issue by elie222** [jonkwheeler/styled-components-snippets#7]
Not really an issue, but posting out of interest. Seems a bit much filling the code base with `Styled` before every component name. What was the reasoning behind this switch?

I'm personally going to switch back to the old snippets this package provided.

**Comment by jonkwheeler** [comment]
@elie222 It's apart of a methodology I preach. I believe all S-C's should be prefixed with `Styled` so the second you or someone else edits the code again, they know they are dealing with a component that is an S-C, and not a normal React component. I suppose I can remove it since it's more a personal preference.

**Comment by jonkwheeler** [comment]
I went ahead and published `styled-components-snippets@v0.9.0`.
